In [3]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

pd.__version__

'3.0.5'

In [9]:
score = [['홍길동', 100, 90, 80],
         ['정약용', 80, 90, 100],
         ['큐리', 100, 90, 30]]
score_df = pd.DataFrame(score, columns=['이름', '국어', '영어', '수학'])
score_df

    이름   국어  영어   수학
0  홍길동  100  90   80
1  정약용   80  90  100
2   큐리  100  90   30

In [7]:
score_df.drop(['국어'], axis=1)

    이름  영어  수학
0  홍길동  90  80

In [10]:
score_df.reset_index(drop=True)

    이름   국어  영어   수학
0  홍길동  100  90   80
1  정약용   80  90  100
2   큐리  100  90   30